[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/staccato2011/*"
  to = "/staccato2011/index.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
